FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && apt-get install -y \
    python3 python3-pip \
    hping3 \
    nmap \
    hydra \
    iproute2 \
    iputils-ping \
    curl wget \
    bash \
    iperf3 \
    netcat-openbsd \
    tcpdump \
    && rm -rf /var/lib/apt/lists/*


RUN pip3 install paramiko psutil requests


